### ISSUE TITLE
Error with NGBoost

### ISSUE THREAD

**Issue by vthost** [aspuru-guzik-group/dionysus#1]
Thank you for providing all this code!
I am trying to use the models in my code and GP works fine, but with NGB I get the below error on Bace. Only for binary classification, regression works. Did you maybe come across this in the past? It seems this (0,5)-sized array is generated...
```
  File "/git/.../wrappers/dionysus.py", line 57, in fit
    self.model.train(dx, dy, hp, verbose=False)
  File "/git/dionysus/dionysus/models/ngb.py", line 34, in train
    self.model[i].fit(x.train, y.train[:, i], x.val, y.val[:, i], early_stopping_rounds=hp.patience)
  File "/opt/anaconda3/envs/dio/lib/python3.8/site-packages/ngboost/ngboost.py", line 271, in fit
    D = self.Manifold(P_batch.T)
  File "/opt/anaconda3/envs/dio/lib/python3.8/site-packages/ngboost/distns/categorical.py", line 62, in __init__
    self.logits[1:K, :] = params  # default the 0th class logits to 0
ValueError: could not broadcast input array from shape (0,5) into shape (1,5)
```

**Comment by gkwt** [comment]
Hello, thank you for reporting this issue, and sorry for the delay in response.

I have re-run the code for the datasets, and I do not see this error. What version of NGBoost are you using? For me v0.3.13 and v0.4.1 worked. Is this error happening for a specific feature?

**Comment by vthost** [comment]
Thanks for getting back to me directly! I had to debug a bit more, it seems to be an unlucky split: https://github.com/stanfordmlgroup/ngboost/issues/307
